name:                brotpreis
version:             0.1.0.0
github:              "FridoSa/brotpreis"
license:             BSD3
author:              "Fridolin Sack"
maintainer:          "fridolin.sack@web.de"
copyright:           "2021 Fridolin Sack"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/FridoSa/brotpreis#readme>

dependencies:
- base >= 4.7 && < 5
- directory

library:
  source-dirs: src

executables:
  brotpreis-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brotpreis

tests:
  brotpreis-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brotpreis
